### ISSUE TITLE
Gatsby themes should use the default webpack config

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-theme-examples#10]
Gatsby themes should use the default webpack config to compile their files unless the user overrides the webpack config, at which point we could introduce a helper to merge the two configs.

This allows authors to ship uncompiled code

**Comment by wcastand** [comment]
Hi, i'm working on a Gatsby theme, it's working fine in a monorepo but i get an error as soon as i try to use it outside of the monorepo, could it be related to this issue?
![image](https://user-images.githubusercontent.com/2178244/53953039-495e5080-40ca-11e9-9a00-9be247cb1cf4.png)
EDIT:
my bad found this closed issue, probably the same error for me
https://github.com/ChristopherBiscardi/gatsby-theme-examples/issues/12

**Comment by ChristopherBiscardi** [comment]
yeah, it's the same issue. We're going to put the webpack config in core so people in userland don't have to do it themselves.
