### ISSUE TITLE
[Question] Will it be possible to share configuration like linting?

### ISSUE THREAD

**Issue by maecapozzi** [ChristopherBiscardi/gatsby-theme-examples#17]
As I'm playing around with these example themes, I was wondering if it will be possible to share configuration (like linting), with the applications consuming my themes. Is there a way for those applications to inherit those scripts?

**Comment by ChristopherBiscardi** [comment]
Yeah, for internal use cases like distributing a theme to be used when starting new company projects, you can take advantage of lifecycle methods like [onPreBootstrap](https://www.gatsbyjs.org/docs/node-apis/#onPreBootstrap) to ensure a specific `.eslint.js` (or any other file, etc) exists.

If the theme is being published to the npm registry it gets a little trickier in terms of figuring out whether or not you *should* override someone's eslint config.

You can use this approach to do as much or as little work as you want including things like modifying `package.json` scripts to make sure they include a specific set, setting up required directories, etc. There are no "built-in helpers" though, so you'll be writing the code to do the actual file creation/modification on your own for configuration of tools that are outside of Gatsby's ownership.

---

It can also be useful to use a starter in combination with a theme where the starter includes any npm package.json scripts and demo content you want to include that can be modified and deleted
