### ISSUE TITLE
Cannot resolve shadow components when jsx extension is used

### ISSUE THREAD

**Issue by loremipson** [ChristopherBiscardi/gatsby-theme-examples#21]
Naming shadow components as `FileName.js` works, but `FileName.jsx` fails:

`Error: Cannot find module '/path/from/dirname/Filename'`

**Comment by ChristopherBiscardi** [comment]
yeah, looks like a bug. Reproduced in https://github.com/ChristopherBiscardi/gatsby-theme-examples/tree/jsx-extension-bug

**Comment by ChristopherBiscardi** [comment]
I have a fix for this locally, just need to test it a bit more
