### ISSUE TITLE
How to override styles files provided by theme?

### ISSUE THREAD

**Issue by sasivarnan** [ChristopherBiscardi/gatsby-theme-examples#22]
Is it possible to add a CSS file to override the styles that are provided as part of the theme?

Any recommended approach for this use case?

**Comment by loremipson** [comment]
We're doing this with [emotion](https://emotion.sh/docs/introduction). Have a core theme using their `ThemeProvider` that any child theme can shadow or extend.

All other components are styled with either emotion's `css` or `styled`, so when they're shadowed they can be overwritten there too.
