### ISSUE TITLE
Shadow component logging

### ISSUE THREAD

**Issue by loremipson** [ChristopherBiscardi/gatsby-theme-examples#24]
When shadowing components, it can easily become pretty confusing to know _where_ in this folder structure the shadowing is actually happening, especially when it is several levels deep. It would be nice if Gatsby, when themes are used, could show when/where it happens.

Perhaps just showing something in the terminal logs, could visually display the shadowing chain? Not really sure the best way to go about this, but thinking of something like this:

```
ComponentX originated in gatsby-theme-core
ComponentX was shadowed by gatsby-theme-blog-a
ComponentX was shadowed by gastby-theme-blog-b
```

**Comment by ChristopherBiscardi** [comment]
We're planning some CLI tooling for this, including ejection support and displaying shadowed paths. Have not begun work on it yet though.

**Comment by ChristopherBiscardi** [comment]
in the meantime, there are [debug logs](https://github.com/gatsbyjs/gatsby/blob/a5dbe7e71771beb055a394e5f8b11b6a73a0fa98/packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js#L77) that will display checked paths for components. `DEBUG=gatsby* gatsby develop` will show them.

**Comment by loremipson** [comment]
Thanks, I don't have `debug` in mine, but can certainly add it in until something more integrated is supported.

**Comment by ChristopherBiscardi** [comment]
`debug` comes with gatsby, so you should be able to use it from the cli as I showed above without doing custom implementation work.
