### ISSUE TITLE
Path does not exist

### ISSUE THREAD

**Issue by mehtavishwa30** [ChristopherBiscardi/gatsby-theme-examples#27]
On running the `yarn workspace starter develop` command it returned the following path not found error.

![Screen Shot 2019-05-17 at 10 29 37 PM](https://user-images.githubusercontent.com/32997409/57944044-5762f580-78f3-11e9-8bea-b6a930a5c0e5.png)

starter is my workspace name for the site that I am building for the Gatsby Themes. 

Following is the code for the `gatsby-plugin-page-creator` in `gatsby-config.js` file

![Screen Shot 2019-05-17 at 10 31 47 PM](https://user-images.githubusercontent.com/32997409/57944184-c7717b80-78f3-11e9-88a6-de07b301c8ce.png)

It says the path passed for the plugin is not found in my device directory. Please help in resolving this error. 

Thanks!

**Comment by ChristopherBiscardi** [comment]
you probably need `path: path.join(__dirname, 'src/pages')` but it's hard to say without seeing an example repo. The problem you're running into is that the `${__dirname}/src/pages` ends up looking for a directory that doesn't exist. You could log out that string to see where it's looking for the directory and change it to where you want it to look. The other possibility is that it's looking in the right place, but `src/pages` doesn't exist and you need to `mkdir -p` it in `onPreBootstrap` or in your starter.
