### ISSUE TITLE
overwrite 

### ISSUE THREAD

**Issue by signalwerk** [ChristopherBiscardi/gatsby-theme-examples#4]
How can I overwrite `siteMetadata`?

```
module.exports = {
  __experimentalThemes: [
    [
      "gatsby-theme-signalwerk",
      {
        root: __dirname,
        siteMetadata: {
          title: 'Not Here A',
        },
      }
    ]
  ], 

  siteMetadata: {
    title: 'Not Here B',
  },
};
```

**Comment by signalwerk** [comment]
To be clear. In the theme in `templates/blog-post.js` there is `<h1>{post.frontmatter.title}</h1>` and I would like to pass in data from the site.

**Comment by signalwerk** [comment]
sorry... I think this works actually

**Comment by ChristopherBiscardi** [comment]
I see you've found it works, but it is also intended to work. The merge function for siteMetadata does a deep merge of the keys with the site's siteMetadata being the last object merged
